#!/usr/bin/python
from optparse import OptionParser, make_option
import sys
import dbus

bus = dbus.SystemBus()

option_list = [ make_option("-p", "--path", action="store", type="string", dest="path"), ]
parser = OptionParser(option_list=option_list)

(options, args) = parser.parse_args()

if (len(args) < 1):
        print("Usage: %s <command>" % (sys.argv[0]))
        print("")
        print("  info")
        print("  add [Id] [Ip] [Port]")
        print("  remove [source path]")
        sys.exit(1)

cmd = args[0]
if (options.path):
	path = options.path
else:
	path = "/"

props = dbus.Interface(bus.get_object("br.org.cesar.modbus", path), "org.freedesktop.DBus.Properties")
manager = dbus.Interface(bus.get_object("br.org.cesar.modbus", path), "br.org.cesar.modbus.Manager1")

if (cmd == "info"):
	print (props.GetAll("br.org.cesar.modbus.Manager1"))
	sys.exit(0)

if (cmd == "add"):
        print ("Adding source:")
        print ("  Id:  %s" % args[1])
        print ("  Ip:  %s" % args[2])
        print ("  Port:  %s" % args[3])
        idval = dbus.String(args[1])
        ipval = dbus.String(args[2])
        portval = dbus.Int32(args[3])
        source_dict = dict()
        source_dict.update({"Id": idval})
        source_dict.update({"Ip": ipval})
        source_dict.update({"Port": portval})
        dbus_dict = dbus.Dictionary(source_dict, signature='sv')
        print (manager.AddSource(dbus_dict))
        sys.exit(0)

if (cmd == "remove"):
	print ("Removing source %s" % args[1])
	devpath = dbus.ObjectPath(args[1])
	print (manager.RemoveSource(devpath))
	sys.exit(0)
