#!/usr/bin/python
from argparse import ArgumentParser
import sys
import dbus


def main(args):
    if (args.help == True):
        print("Usage: {} [-h] [-a NAME TYPE UNIT OFFSET] [-c N] [-l] [-rm PATH] [-p"
                " PATH]".format(sys.argv[0]))
        print("")
        print("Optional arguments:")
        print("  -a NAME TYPE UNIT OFFSET , --add NAME TYPE UNIT OFFSET\n"
              "                   adds a new source to an slave\n"
              "                   NAME = string\n"
              "                   TYPE = bool(b),byte(y),uint16(q),uint32(u)\n"
              "                   UNIT = string\n"
              "                   OFFSET = int\n"
              "                   add the slave path is required")
        print("  -h, --help       show this help message and exit")
        print("  -l, --list       list all sources in a given slave")
        print("  -p PATH, --path PATH  \n"
              "                   specify the slave's path whose sources will\n"
              "                   be manipulated")
        print("  -rm SOURCEPATH, --remove SOURCEPATH\n"
              "                   remove a given source. slave path is required")
        print("  -A ADDRESS, --dbus-address ADDRESS\n"
              "                        dbus address to connect")
        return 0

    if (args.address):
        bus = dbus.bus.BusConnection(args.address)
    else:
        bus = dbus.SystemBus()

    if (args.path):
        obj = bus.get_object("br.org.cesar.modbus", args.path)
        props = dbus.Interface(obj, "org.freedesktop.DBus.Properties")
        slave = dbus.Interface(obj, "br.org.cesar.modbus.Slave1")
    else : 
        print("No slave path given. See help")
        return 1

    if (args.list == True):
        list_obj = bus.get_object("br.org.cesar.modbus","/")
        iface = dbus.Interface(list_obj,"org.freedesktop.DBus.ObjectManager")
        sources = []
        for aux in iface.GetManagedObjects():
                var = aux.split("/")
                if ("/" + var[1] == args.path):
                    try:
                        sources.append(var[2])
                    except:
                        continue
        if not sources:
            print("No sources in: {}".format(args.path))
            return 0
        else:
            print("Sources in {}: \n {}".format(args.path,sources))
            return 0

    if (args.add != None):
        print ("Adding source:")
        print ("  Name:  {}".format(args.add[0]))
        print ("  Type:  {}".format(args.add[1]))
        print ("  Unit:  {}".format(args.add[2]))
        print ("  Address:  {}".format(args.add[3]))

        nameval = dbus.String(args.add[0])
        typeval = dbus.String(args.add[1])
        unitval = dbus.String(args.add[2])
        addrval = dbus.UInt16(args.add[3])
        slave_dict = dict()
        slave_dict.update({"Name": nameval})
        slave_dict.update({"Type": typeval})
        slave_dict.update({"Unit": unitval})
        slave_dict.update({"Address": addrval})
        dbus_dict = dbus.Dictionary(slave_dict, signature='sv')
        print ("PATH: {}".format(slave.AddSource(dbus_dict)))
        return 0


    if (args.remove != None):
        print ("Removing source {}".format(args.remove))
        devpath = dbus.ObjectPath(args.path+args.remove)
        print (slave.RemoveSource(devpath))
        return 0

if __name__ == "__main__":
    parser = ArgumentParser(prog="./test-slave", add_help=False)
    parser.add_argument("-p", "--path", action="store", type=str)
    parser.add_argument('-A', '--dbus-address', dest="address", type=str)
    parser.add_argument("-a", "--add", action ="store", type=str, nargs=4)
    parser.add_argument("-h", "--help", action="store_true")
    parser.add_argument("-l", "--list", action="store_true")
    parser.add_argument("-rm","--remove",action="store",type=str)
    args = parser.parse_args()
    ret = main(args)
    sys.exit(ret)
